# Generated by Django 4.1.3 on 2023-04-21 12:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
                ('image1', models.ImageField(default='sample_suite.png', upload_to='suites', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('image2', models.ImageField(default='sample_suite.png', upload_to='suites', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('image3', models.ImageField(default='sample_suite.png', upload_to='suites', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('logo', models.ImageField(default='sample.png', upload_to='logos', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('wifi', models.BooleanField()),
                ('pickup', models.BooleanField()),
                ('water', models.BooleanField()),
                ('allService', models.BooleanField()),
                ('telephone', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('In Process', 'In Process'), ('Cancled', 'Cancled')], default='In Process', max_length=100)),
                ('accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.accomodations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accomodations',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotels'),
        ),
    ]
